export const FETCH_DEBIT_MONEY ="FETCH_DEBIT" 
export const FETCH_CREDIT ="FETCH_CREDIT" 
export const FETCH_DATA ="FETCH_DATA"
export const SET_DATA ="SET_DATA" 
export const SEND_MONEY_SAGA = 'SEND_MONEY_SAGA'
export const FETCH_ACCOUNT_BALANCE = "FETCH_ACCOUNT_BALANCE "
export const SET_ACCOUNT_BALANCE = "SET_ACCOUNT_BALANCE";
export const SAVE_DEPOSIT = 'SAVE_DEPOSIT';
export const SAVE_DEPOSIT_SUCCESS = 'SAVE_DEPOSIT_SUCCESS';
export const DEPOSIT_STATUS_RESET = 'DEPOSIT_STATUS_RESET';
export const  ADD_TO_BALANCE = 'ADD_TO_BALANCE';




